name: food_scan_app
description: "Food Scan App — proyek akhir kelas Belajar Penerapan Machine Learning untuk Flutter (Dicoding) oleh Fareynaldi."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  flutter_litert: ^3.5.1
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/aiy_food_v1.tflite
    - assets/models/labels.txt
