{
 "title": "Dashboard-fareynaldi",
 "tags": [
  "titanic",
  "pidi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Inference Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "titanic_inference_requests_total",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Inference Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(titanic_inference_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Avg Inference Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(titanic_inference_latency_seconds_sum[1m]))/sum(rate(titanic_inference_latency_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Survival Predictions by Class",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "titanic_survival_predictions_total",
     "legendFormat": "class {{label}}"
    }
   ]
  },
  {
   "title": "Service CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "service_cpu_percent" }
   ]
  },
  {
   "title": "Service Memory (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "service_memory_percent" }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "service_inflight_requests" }
   ]
  }
 ]
}