name: CI Titanic - Retrain

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn==1.7.2 pandas==2.3.3 numpy

      - name: Train via MLflow Project
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local --experiment-name "Titanic_Survival_CI"

      - name: List training output
        working-directory: MLProject
        run: |
          echo "Hasil training (mlruns):"
          ls -R mlruns | head -40
