{
 "title": "Dafina Meira Rizkia",
 "tags": [
  "penguin",
  "smsml"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Laju Request API (per endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(penguin_api_requests_total[1m])",
     "legendFormat": "{{endpoint}} ({{status}})"
    }
   ]
  },
  {
   "title": "Rata-rata Latensi Inferensi (detik)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(penguin_inference_latency_seconds_sum[5m])) / clamp_min(sum(rate(penguin_inference_latency_seconds_count[5m])), 0.0001)",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Total Prediksi per Spesies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "penguin_predictions_total", "legendFormat": "{{species}}" }
   ]
  },
  {
   "title": "Pemakaian CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "penguin_service_cpu_percent", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "Pemakaian Memori (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "penguin_service_memory_percent", "legendFormat": "Memory" }
   ]
  }
 ]
}